### ISSUE TITLE
AndroidKeyStore

### ISSUE THREAD

**Issue by lntrx** [rednaga/keystore-shim#1] opened 2019-04-11 12:45 UTC
Hey mate, great writeup! Though I am wondering why it doesn't work with AndroidKeyStore instead of defaultType()

**Comment by strazzere** [comment] 2019-04-11 14:20
Can you provide an example or more details about what you're referencing?

**Comment by lntrx** [comment] 2019-04-11 19:07
// KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());
instead of  this if you try KeyStore.getInstance("AndroidKeyStore") it will throw error

**Comment by strazzere** [comment] 2019-04-11 19:28
Per
https://developer.android.com/reference/java/security/KeyStore.html#getInstance(java.lang.String)
 ;

Throws
KeyStoreException
<https://developer.android.com/reference/java/security/KeyStoreException.html>
if
no Provider supports a KeyStoreSpi implementation for the specified type.

Is this because there is no provider for "AndroidKeyStore"? What is the
error being throw? Can you provide a reproducible example?

AFAIK, this is essentially working as expected...

-Tim Strazzere

**Comment by lntrx** [comment] 2019-04-11 19:42
Thank you for response mate. My computer doesn't work now, but the error was AndroidKeyStore wasn't found or not supported. Something like that. 

That's the case because apps generally use AndroidKeyStore type<https://developer.android.com/training/articles/keystore#java>. Normally there's provider<https://android.googlesource.com/platform/frameworks/base/+/c58153b/keystore/java/android/security/keystore/AndroidKeyStoreSpi.java>. I don't know why it says it couldn't find the type

**Comment by strazzere** [comment] 2019-04-11 20:05
Hard to pin down without an explicit example.

However my gut says, if it isn't working for this application. Then it
wasn't working in the target application.

Throwing an exception is acceptable and expected use-case.

-Tim Strazzere

**Comment by strazzere** [comment] 2019-04-18 18:23
Going to close this for the time, but feel free to reopen it if there is more information that can be provided or if we can nail down that this exception should not be getting thrown.

**Closed as completed by strazzere** 2019-04-18 18:23 UTC
